name: pehle_workflow
on:
  workflow_dispatch:
jobs:
  my_first_job:
    name: test job
    runs-on: self-hosted
    steps:
      - name: Display the path
        shell: cmd
        run: echo Hello World
